language: python
cache: pip
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37-plain
before_install:
  - sudo rm -rf /var/lib/redis/*
  - wget https://github.com/antirez/redis/archive/6.0-rc4.tar.gz && mkdir redis_install && tar -xvzf 6.0-rc4.tar.gz -C redis_install && cd redis_install/redis-6.0-rc4 && make && src/redis-server --daemonize yes && cd ../..
  - redis-cli info
install:
  - pip install codecov tox
script:
  - tox
after_success:
  - "if [[ $TOXENV != 'flake8' ]]; then codecov; fi"
